name: Cypress E2E (OrangeHRM + ChatBot)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch: 

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cypress-io/github-action@v6
        with:
          command: npm run cy:test:all

      - name: Merge & generate Mochawesome report
        run: |
          npm run merge-reports
          npm run generate-report

      - name: Upload Mochawesome report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/*.html
          if-no-files-found: error